# Generated by Django 2.2 on 2020-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.CharField(default='Группа не указана', max_length=200),
        ),
    ]
